apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::307287463250:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-X9VI86K5KRQO
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::307287463250:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-29T07:41:44Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "4819"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 38be0b4d-f37c-4f31-b503-c3761f82088b
