apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::307287463250:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1U72HBZXND67L
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::307287463250:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-30T01:50:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "795"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: fd92016e-d7ec-4ad8-8dc2-029f22d2300b
